name: Go CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          check-latest: true 

      - name: Install Dependencies
        run: go mod download

      - name: Verify API Build
        run: go build -o /dev/null ./cmd/api/main.go

      - name: Verify Worker Build
        run: go build -o /dev/null ./cmd/worker/main.go

      - name: Validate Dockerfile Build
        # Menggunakan build biasa tanpa simpan image untuk hemat waktu
        run: docker build .